# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65vent.proto\"%\n\x12\x43reateEventRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x15\n\x13\x43reateEventResponse2B\n\x05\x45vent\x12\x39\n\npost_event\x12\x13.CreateEventRequest\x1a\x14.CreateEventResponse\"\x00\x62\x06proto3')



_CREATEEVENTREQUEST = DESCRIPTOR.message_types_by_name['CreateEventRequest']
_CREATEEVENTRESPONSE = DESCRIPTOR.message_types_by_name['CreateEventResponse']
CreateEventRequest = _reflection.GeneratedProtocolMessageType('CreateEventRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEEVENTREQUEST,
  '__module__' : 'event_pb2'
  # @@protoc_insertion_point(class_scope:CreateEventRequest)
  })
_sym_db.RegisterMessage(CreateEventRequest)

CreateEventResponse = _reflection.GeneratedProtocolMessageType('CreateEventResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEEVENTRESPONSE,
  '__module__' : 'event_pb2'
  # @@protoc_insertion_point(class_scope:CreateEventResponse)
  })
_sym_db.RegisterMessage(CreateEventResponse)

_EVENT = DESCRIPTOR.services_by_name['Event']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEEVENTREQUEST._serialized_start=15
  _CREATEEVENTREQUEST._serialized_end=52
  _CREATEEVENTRESPONSE._serialized_start=54
  _CREATEEVENTRESPONSE._serialized_end=75
  _EVENT._serialized_start=77
  _EVENT._serialized_end=143
# @@protoc_insertion_point(module_scope)
